FROM node:12
MAINTAINER Brian H Wilson "brian@wildsong.biz"
#ENV NODE_ENV production

WORKDIR /home/node

RUN npm install parcel -g && npm install serve -g 

WORKDIR /home/node/react-cap
RUN chmod 755 start_server.sh

EXPOSE 5000/tcp
CMD start_server.sh
