# Just the database, exposed so we can develop the API and client on Plover
#   mysql
#   a volume to persist sql database
version: '3.6'
services:
    db:
        container_name: cap-mysql
        image: mysql
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            # This database will be created if it does not exist.
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            # The database will be owned by this user/pass
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        expose:
            - 3306
        ports:
            - 3306:3306
        networks:
            - proxy_net
        volumes:
            - cap_data:/var/lib/mysql
        restart: unless-stopped

volumes:
    cap_data:
        name: cap_data
networks:
    proxy_net:
        name: proxy_net
        external: true
