FROM node:12
MAINTAINER Brian H Wilson "brian@wildsong.biz"
#ENV NODE_ENV production

WORKDIR /home/node

# My build context should be in the server/ folder
COPY . .
RUN npm install

EXPOSE 3000/tcp
CMD npm start
