FROM node:12
MAINTAINER Brian H Wilson "brian@wildsong.biz"

WORKDIR /home/node

# Download the code
RUN git clone https://github.com/brian32768/react-cap.git

WORKDIR /home/node/react-cap/server
RUN npm install
#RUN npm run build

EXPOSE 3000/tcp

CMD npm start
