FROM node:12
MAINTAINER Brian H Wilson "brian@wildsong.biz"
#ENV NODE_ENV production

WORKDIR /home/node
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install && mv node_modules ../
COPY . .
EXPOSE 3000/tcp
CMD npm start
